language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm run lerna run prepublish
script:
  - npm test